In [ ]:
%matplotlib widget

read file

In [ ]:
import numpy as np
    
raw_data = np.fromfile(r"C:\Files\Research\dataSet0\norm_ct.001.raw", dtype=np.float32).reshape((160,224,168))
print(raw_data.shape)

test generate mask

In [1]:
import numpy as np
import tools

# raw_data = np.fromfile(r"C:\Files\Research\dataSet0\norm_ct.001.raw", dtype=np.float32).reshape((160,224,168))
raw_data = np.fromfile(r"C:\Files\Research\dataSet2\original_volume_001.raw", dtype=np.float32).reshape((128,128,128))
print("raw_data.shape:",raw_data.shape)

mask_volume,mask = tools.generate_mask(raw_data.shape,7)

new_data = raw_data * (1-mask_volume)
new_data.astype('float32').tofile(r"C:\Files\Research\dataSet2\atest001.raw")

raw_data.shape: (128, 128, 128)


volume crop

In [29]:
import numpy as np
# import tools

# def crop_raw(origin_pos,new_pos,size=(128,128,128)):
origin_pos = "/Users/wanglikai/Codes/Volume_Complete/dataSet0/norm_mr.001.raw"
new_pos = "/Users/wanglikai/Codes/test/norm_ct.001.raw"
size = (128,128,128)
# read original volume data.
old_data = np.fromfile(origin_pos, dtype=np.float32).reshape(160,224,168)
assert (old_data.shape[0]>=size[0] and old_data.shape[1]>=size[1] and old_data.shape[2]>=size[2])
n_range_r = old_data.shape[0]-size[0]
y_range_l = old_data.shape[1]-size[1]
z_range_l = int(old_data.shape[2]/2-size[2]/2)
z_range_r = int(old_data.shape[2]/2+size[2]/2)
new_data = old_data[:10,:10]
# new_data = old_data[range(n_range_r)][range(y_range_l,size[1])][range(z_range_l,z_range_r)]
new_data = old_data[old_data.shape[0]-size[0]:,old_data.shape[1]-size[1]-10:old_data.shape[1]-size[1]+118,int(old_data.shape[2]/2-size[2]/2):int(old_data.shape[2]/2+size[2]/2)]
# 取n=[32:160],h=[86:214],w=[20:148]
new_data.astype('float32').tofile(new_pos)


# crop_raw("/Users/wanglikai/Codes/Volume_Complete/dataSet0/norm_ct.001.raw","/Users/wanglikai/Codes/test/norm_ct.001.raw",size=(128,128,128))

In [37]:
size=(128,128,128)
origin_pos = "/Users/wanglikai/Codes/Volume_Complete/dataSet0/norm_ct.001.raw"
new_pos = "/Users/wanglikai/Codes/test/norm_ct.001.raw"
# read original volume data.
fileName = origin_pos
old_data = np.fromfile(fileName, dtype=np.float32).reshape(160,224,168)
assert (old_data.shape[0]>=size[0] and old_data.shape[1]>=size[1] and old_data.shape[2]>=size[2])

# 取n=[32:160],h=[86:214],w=[20:148]最合适
new_data = old_data[old_data.shape[0]-size[0]         :,
                    old_data.shape[1]-size[1]-10      :old_data.shape[1]-size[1]+118,
                    int(old_data.shape[2]/2-size[2]/2):int(old_data.shape[2]/2+size[2]/2)]

new_data.astype('float32').tofile(new_pos)

In [2]:
import tools

origin_pos = "/Users/wanglikai/Codes/Volume_Complete/dataSet0/norm_ct.001.raw"
new_pos = "/Users/wanglikai/Codes/test/norm_ct.001.raw"
tools.crop_raw_128(origin_pos=origin_pos,new_pos=new_pos)


In [2]:
import torch
from torch.utils.data import DataLoader, TensorDataset

# 假设你有一些数据
data = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

# 假设你有一些标签
labels = torch.tensor([0, 1, 0, 1, 0])

# 创建一个 TensorDataset 对象，将数据和标签组合起来
dataset = TensorDataset(data, labels)

# 使用 DataLoader 加载数据集，并设置 batch size 为 2
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# 迭代 DataLoader 并获取每个批次的数据
for batch_data, batch_labels in dataloader:
    print("Batch Data:")
    print(batch_data)
    print("Batch Labels:")
    print(batch_labels)
    print()


Batch Data:
tensor([[3, 4],
        [1, 2]])
Batch Labels:
tensor([1, 0])

Batch Data:
tensor([[7, 8],
        [5, 6]])
Batch Labels:
tensor([1, 0])

Batch Data:
tensor([[ 9, 10]])
Batch Labels:
tensor([0])

